### ISSUE TITLE
Tool bar icons vanish if the tool window gets too narrow

### ISSUE THREAD

**Issue by MartinL0815** [majorimi/vs-reopen#11]
Since the right tool bar icons seem to be "aligned" to the right edge of the window and seem to have a constant padding to the left tool bar icons.
Shrinking the width of the tool window cause those right icons to be inaccessible.

There is no need to shrink the widht manually, it is sufficient to dock the tool window to right or left to be automatically hidden if unused. This process sets the width of the window and lets become the right icons invisible and inaccessible.

**Comment by majorimi** [comment]
Thanks for your feedback. I reproduced it. fixing it on v. 1.4.4

**Comment by majorimi** [comment]
Fix deployed in version 1.4.4. Let me know how is it working for you.
